cd profiles;/share/instsww/cadence/QUANTUS.22.11.000/bin/Techgen  -rcgen --with_hmg  -generate  dsample.ict 0 -1 450 6 0 1 2 3 0 0 0 1 0 0 0;  perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/process_xover_inputs.pl -prof  6_POLY_3_METAL_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE  -nbors 3 -out xover; cd 6_POLY_3_METAL_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE;cp 6_POLY_3_METAL_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE.dat 6_POLY_3_METAL_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE.dat3d;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/randomize.pl xover;mv xover_rnd 6_POLY_3_METAL_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE.dat;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/reflect_profiles.pl 6_POLY_3_METAL_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE  7 5 ;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/generate_model_adaptive_test.pl  6_POLY_3_METAL_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE profiles models  7 24 5 .95 50 2  /share/instsww/cadence/QUANTUS.22.11.000/bin/mg dsample.ict;

cd profiles;/share/instsww/cadence/QUANTUS.22.11.000/bin/Techgen  -rcgen --with_hmg  -generate  dsample.ict 0 -1 450 6 0 2 2 3 0 0 0 1 0 0 0;  perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/process_xover_inputs.pl -prof  6_METAL_3_METAL2_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE  -nbors 3 -out xover; cd 6_METAL_3_METAL2_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE;cp 6_METAL_3_METAL2_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE.dat 6_METAL_3_METAL2_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE.dat3d;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/randomize.pl xover;mv xover_rnd 6_METAL_3_METAL2_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE.dat;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/reflect_profiles.pl 6_METAL_3_METAL2_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE  7 5 ;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/generate_model_adaptive_test.pl  6_METAL_3_METAL2_0_CSUBSTRATE_0_NONE_0_CSUBSTRATE profiles models  7 24 5 .95 50 2  /share/instsww/cadence/QUANTUS.22.11.000/bin/mg dsample.ict;

cd profiles;/share/instsww/cadence/QUANTUS.22.11.000/bin/Techgen  -rcgen --with_hmg  -generate  dsample.ict 0 -1 450 6 0 2 2 0 3 0 0 0 1 0 0;  perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/process_xover_inputs.pl -prof  6_METAL_0_NONE_3_POLY_0_NONE_0_CSUBSTRATE  -nbors 3 -out xover; cd 6_METAL_0_NONE_3_POLY_0_NONE_0_CSUBSTRATE;cp 6_METAL_0_NONE_3_POLY_0_NONE_0_CSUBSTRATE.dat 6_METAL_0_NONE_3_POLY_0_NONE_0_CSUBSTRATE.dat3d;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/randomize.pl xover;mv xover_rnd 6_METAL_0_NONE_3_POLY_0_NONE_0_CSUBSTRATE.dat;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/reflect_profiles.pl 6_METAL_0_NONE_3_POLY_0_NONE_0_CSUBSTRATE  7 5 ;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/generate_model_adaptive_test.pl  6_METAL_0_NONE_3_POLY_0_NONE_0_CSUBSTRATE profiles models  7 24 5 .95 50 2  /share/instsww/cadence/QUANTUS.22.11.000/bin/mg dsample.ict;

cd profiles; /share/instsww/cadence/QUANTUS.22.11.000/bin/Techgen  -rcgen --with_hmg   -generate  dsample.ict 0 -1 19 6 0 2 2 3 3 0 0 1 1 0 0; cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/generate_model_adaptive_test.pl  6_METAL_3_METAL2_3_POLY_0_NONE_0_CSUBSTRATE profiles models   1 8 1 .9 50 2  /share/instsww/cadence/QUANTUS.22.11.000/bin/mg dsample.ict;

cd profiles;/share/instsww/cadence/QUANTUS.22.11.000/bin/Techgen  -rcgen --with_hmg  -generate  dsample.ict 0 -1 450 6 0 3 2 0 3 0 0 0 1 0 0;  perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/process_xover_inputs.pl -prof  6_METAL2_0_NONE_3_METAL_0_NONE_0_CSUBSTRATE  -nbors 3 -out xover; cd 6_METAL2_0_NONE_3_METAL_0_NONE_0_CSUBSTRATE;cp 6_METAL2_0_NONE_3_METAL_0_NONE_0_CSUBSTRATE.dat 6_METAL2_0_NONE_3_METAL_0_NONE_0_CSUBSTRATE.dat3d;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/randomize.pl xover;mv xover_rnd 6_METAL2_0_NONE_3_METAL_0_NONE_0_CSUBSTRATE.dat;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/reflect_profiles.pl 6_METAL2_0_NONE_3_METAL_0_NONE_0_CSUBSTRATE  7 5 ;cd ..;perl /home/aa/users/cs199-cwg/aureoProject/aureo-pdk/debugTech/testConformal2/.tech_scripts/generate_model_adaptive_test.pl  6_METAL2_0_NONE_3_METAL_0_NONE_0_CSUBSTRATE profiles models  7 24 5 .95 50 2  /share/instsww/cadence/QUANTUS.22.11.000/bin/mg dsample.ict;

